/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as GmailRouteImport } from './routes/gmail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApplicationsIdRouteImport } from './routes/applications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailRoute = GmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/gmail': typeof GmailRoute
  '/login': typeof LoginRoute
  '/applications/$id': typeof ApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/gmail': typeof GmailRoute
  '/login': typeof LoginRoute
  '/applications/$id': typeof ApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/gmail': typeof GmailRoute
  '/login': typeof LoginRoute
  '/applications/$id': typeof ApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/applications' | '/gmail' | '/login' | '/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/applications' | '/gmail' | '/login' | '/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/gmail'
    | '/login'
    | '/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  GmailRoute: typeof GmailRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail': {
      id: '/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof GmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof ApplicationsRoute
    }
  }
}

interface ApplicationsRouteChildren {
  ApplicationsIdRoute: typeof ApplicationsIdRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsIdRoute: ApplicationsIdRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  GmailRoute: GmailRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
