/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as GmailRouteImport } from './routes/gmail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApplicationsIdRouteImport } from './routes/applications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailRoute = GmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai': typeof AiRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/automation': typeof AutomationRoute
  '/gmail': typeof GmailRoute
  '/login': typeof LoginRoute
  '/applications/$id': typeof ApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai': typeof AiRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/automation': typeof AutomationRoute
  '/gmail': typeof GmailRoute
  '/login': typeof LoginRoute
  '/applications/$id': typeof ApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai': typeof AiRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/automation': typeof AutomationRoute
  '/gmail': typeof GmailRoute
  '/login': typeof LoginRoute
  '/applications/$id': typeof ApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/ai'
    | '/applications'
    | '/automation'
    | '/gmail'
    | '/login'
    | '/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/ai'
    | '/applications'
    | '/automation'
    | '/gmail'
    | '/login'
    | '/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/ai'
    | '/applications'
    | '/automation'
    | '/gmail'
    | '/login'
    | '/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AiRoute: typeof AiRoute
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  AutomationRoute: typeof AutomationRoute
  GmailRoute: typeof GmailRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail': {
      id: '/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof GmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof ApplicationsRoute
    }
  }
}

interface ApplicationsRouteChildren {
  ApplicationsIdRoute: typeof ApplicationsIdRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsIdRoute: ApplicationsIdRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AiRoute: AiRoute,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  AutomationRoute: AutomationRoute,
  GmailRoute: GmailRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
